# Generated by Django 3.0.7 on 2020-06-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logits', models.DecimalField(decimal_places=5, max_digits=10)),
                ('predictionValue', models.PositiveSmallIntegerField()),
                ('predictionText', models.CharField(max_length=15)),
                ('predictionProb', models.DecimalField(decimal_places=4, max_digits=5)),
                ('dataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakeNewsApp.NewsDataModel')),
            ],
        ),
    ]
